### ISSUE TITLE
About Xeddit

### ISSUE THREAD

**Issue by mendel5** [mendel5/alternative-frontends#1]
Hello @ErlingMK ,

I have recently discovered your Xeddit repository at https://github.com/ErlingMK/Xeddit . On Github, you are the owner and sole contributor of Xeddit.

However I've noticed there is also a Xeddit repository on Gitlab, see https://gitlab.com/xeddit/xeddit .

Are you the original author of Xeddit?

**Comment by ErlingMK** [comment]
Hello! I'm not the owner of Xeddit on gitlab. Wasn't aware it existed

**Comment by mendel5** [comment]
@ErlingMK Ok, thanks for your answer.
What I was wondering is that the initial commit for https://gitlab.com/xeddit/xeddit/-/commits/master was in June 2018 while for https://github.com/ErlingMK/Xeddit/commits/master it was in August 2019.

Do you know who created Xeddit originally?

**Comment by ErlingMK** [comment]
I don't know, sorry

**Comment by mendel5** [comment]
Ok
